site:
  title: OpenNMS Helm Charts
  url: https://github.com/OpenNMS/helm-charts
  start_page: opennmshelmcharts::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      tags:
        - v*
      start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.0.1/ui-bundle.zip
asciidoc:
  attributes:
    stem: latexmath
    tabs: tabs
  extensions:
    - ./docs/lib/tabs-block.js
output:
  clean: true
  dir: ./public
  destinations:
    - provider: fs
    - provider: archive