= Introduction
:imagesdir: ../assets/images
:!sectids:

OpenNMS Helm Charts is based and tested against the latest Horizon.
See the following for version compatibilty:

[options="header"]
[cols="1,1,1"]
|===

| Helm chart version
| Horizon version
| Meridian version

| 1.x
| Horizon 32.x
| Meridian 2023.x
|===

[[requirements]]
== Requirements

Before you begin, ensure that you have a deep understanding of how Kubernetes and Helm work.

The following describes the requirements for your local machine, Kubernetes, and additional external dependencies.
We do not yet support cloud deployments.

=== Local

You must have the following installed on your machine:

* https://kubernetes.io/docs/reference/kubectl/[kubectl]
* https://helm.sh/docs/intro/install/[Helm] version 3
* (optional) https://minikube.sigs.k8s.io/docs/start/[minikube] for testing

//Do we need to include minimum OS requirements?

When using cloud resources, make sure you have https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest[az] for Azure or https://cloud.google.com/sdk/gcloud[gcloud] for Google Cloud.

=== Kubernetes

* A Kubernetes environment running version 1.20 or later (cloud providers, kind, minikube, Docker Desktop, and so on.)

IMPORTANT: Containers are bundled with default plugins.
You can add additional plugins by building your own container image (see https://github.com/OpenNMS/helm-charts/blob/main/kar-container/README.md[kar-container] for an example).

=== External dependencies

Kafka, Elasticsearch, and PostgreSQL running externally (and maintained separately from the solution), all with SSL enabled.

* PostgreSQL server as the central database for OpenNMS and Grafana.
** For Google Cloud, the solution was tested using Google SQL for PostgreSQL with SSL and a private IP.

* Elasticsearch cluster for flow persistence.

* Grafana Loki server for log aggregation.
** https://grafana.com/docs/loki/latest/getting-started/logcli/[logcli] helps extract OpenNMS logs from the command line for troubleshooting purposes.

* https://cert-manager.readthedocs.io/en/latest/[cert-manager] to provide HTTPS/TLS support to the web-based services the ingress controller manages.
** A `ClusterIssuer` to use it across multiple independent OpenNMS installations.

* Nginx Ingress Controller, as the solution has not been tested with other Ingress implementations.
