= Introduction
:imagesdir: ../assets/images
:!sectids:

OpenNMS Helm Charts is based and tested against the latest Horizon.
See the following for version compatibilty:

[options="header"]
[cols="1,1,1"]
|===

| Helm chart version
| Horizon version
| Meridian version

| 1.x
| Horizon 32.x
| Meridian 2023.x
|===

[[requirements]]
== Requirements

Before you begin, ensure that you have a deep understanding of how Kubernetes and Helm work.

The following describes the requirements for your local machine, Kubernetes, and additional external dependencies.
We do not yet support cloud deployments.

=== Local

You must have the following installed on your machine:

* https://kubernetes.io/docs/reference/kubectl/[kubectl]
* https://helm.sh/docs/intro/install/[Helm] version 3
* (optional) https://minikube.sigs.k8s.io/docs/start/[minikube] for testing

//Do we need to include minimum OS requirements?

When using cloud resources, make sure you have https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest[az] for Azure or https://cloud.google.com/sdk/gcloud[gcloud] for Google Cloud.

=== Kubernetes

* A Kubernetes environment running version 1.20 or later (for example, cloud providers, kind, minikube, or Docker Desktop)

IMPORTANT: OpenNMS containers include only the default plugins.
You can add additional plugins by xref:kar-container.adoc[building your own container image].

=== External dependencies

While there are a number of external dependencies that may be used, only a PostgreSQL server is required.
The other services are optional based on your deployment needs.
For production, these services should be running independently of the OpenNMS Kubernetes deployment.
If you want to spin up instances for testing, see `/scripts/start-dependencies.sh`.

* PostgreSQL server as the central database for OpenNMS and Grafana.
** For Google Cloud, this solution was tested using Google SQL for PostgreSQL with SSL and a private IP, and should work similiarly for other cloud-hosted PostgreSQL services.

* Elasticsearch cluster for flow persistence and/or alarm history.

* Grafana Loki server for log aggregation.
** https://grafana.com/docs/loki/latest/getting-started/logcli/[logcli] helps extract OpenNMS logs from the command line for troubleshooting purposes.

* https://cert-manager.readthedocs.io/en/latest/[cert-manager] to provide HTTPS/TLS support to the web-based services the ingress controller manages.
** A `ClusterIssuer` to use it across multiple independent OpenNMS installations.

* Nginx Ingress Controller. This solution has not been tested with other Ingress implementations.
