{{- if .Values.truststore.content }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.minion.name | default  .Release.Name }}-app-jks
data: # To be mounted at /etc/java/jks
  truststore.jks: |
     {{ .Values.truststore.content }}
{{- end }}
