{{- if .Values.truststore.content }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: minion-app-jks
data: # To be mounted at /etc/java/jks
  truststore.jks: |
     {{ .Values.truststore.content }}
{{- end }}
