apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: minion-data-folder
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.minion.configuration.storage.dataFolder | default "1Gi" }}
status: {}
