---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onms-etc-pvc
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    tier: storage
    {{- include "opennms.labels" . | nindent 4 }}
spec:
  accessModes: # Assumes default StorageClass
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.opennms.configuration.storage.etc | default "1Gi" }}
