---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-scripts
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "scripts/**").AsConfig | nindent 2 }}
