---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-credentials
  namespace: {{ .Release.Name }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
  {{- if ((.Values.dependencies).postgresql).username }}
  POSTGRES_USER: {{ .Values.dependencies.postgresql.username | b64enc }}
  {{- end }}
  {{- if ((.Values.dependencies).postgresql).password }}
  POSTGRES_PASSWORD: {{ .Values.dependencies.postgresql.password | b64enc }}
  {{- end }}
  OPENNMS_DBUSER: {{ .Values.core.configuration.database.username | b64enc }}
  OPENNMS_DBPASS: {{ required "Database password (core.configuration.database.password) must be provided" .Values.core.configuration.database.password | b64enc }}
  OPENNMS_HTTP_USER: {{ .Values.core.configuration.http.restUsername | b64enc }}
  OPENNMS_HTTP_PASS: {{ required "REST password (core.configuration.http.restPassword) must be provided" .Values.core.configuration.http.restPassword | b64enc }}
  OPENNMS_ADMIN_PASS: {{ required "HTTP admin password (core.configuration.http.adminPassword) must be provided" .Values.core.configuration.http.adminPassword | b64enc }}
  {{- if ((.Values.dependencies).kafka).username }}
  KAFKA_SASL_USERNAME: {{ .Values.dependencies.kafka.username | b64enc }}
  {{- end }}
  {{- if ((.Values.dependencies).kafka).password }}
  KAFKA_SASL_PASSWORD: {{ .Values.dependencies.kafka.password | b64enc }}
  {{- end }}
  {{- if ((.Values.dependencies).elasticsearch).hostname }}
  {{- if ((.Values.dependencies).elasticsearch).username }}
  ELASTICSEARCH_USER: {{ .Values.dependencies.elasticsearch.username | b64enc }}
  {{- end }}
  {{- if ((.Values.dependencies).elasticsearch).password }}
  ELASTICSEARCH_PASSWORD: {{ .Values.dependencies.elasticsearch.password | b64enc }}
  {{- end }}
  {{- end }}
  {{- if gt ((.Values.grafana).replicaCount|int) 0 }}
  GF_DATABASE_USER: {{ .Values.grafana.configuration.database.username | b64enc }}
  GF_DATABASE_PASSWORD: {{ .Values.grafana.configuration.database.password | b64enc }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.grafana.configuration.ui.adminPassword | b64enc }}
  {{- end }}
  {{- if ((.Values.dependencies).truststore).content }}
  TRUSTSTORE_PASSWORD: {{ .Values.dependencies.truststore.password | b64enc }}
  {{- end }}
