---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-jks
  namespace: {{ .Release.Name }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
data: # To be mounted at /etc/java/jks
  {{- if .Values.dependencies.truststore.content }}
  truststore.jks: |
    {{ .Values.dependencies.truststore.content }}
  {{- end }}
  {{- if .Values.dependencies.postgresql.caCert }}
  postgresql-ca.cert: |
    {{ .Values.dependencies.postgresql.caCert | b64enc }}
  {{- end }}
  {{- if .Values.dependencies.loki.caCert }}
  loki-ca.cert: |
    {{ .Values.dependencies.loki.caCert | b64enc }}
  {{- end }}
