{{- if and (eq (include "onOpenShift" .) "true") ((.Values.dependencies).route) (gt ((.Values.grafana).replicaCount|int) 0) }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana
  namespace: {{ include "namespace" . }}
  labels:
    app: grafana
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: {{ include "core.chart" . }}
spec:
  host: {{ printf "grafana-%s.%s" .Release.Name .Values.domain | quote }}
  to:
    kind: Service
    name: grafana
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: {{ printf "grafana-%s.%s" .Release.Name .Values.domain | quote }}
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
      wildcardPolicy: None
{{- end }}