{{- define "core.grafanaDSOptions" -}}
{{- $srv := "onms-core" -}}
{{- $namespace := include "namespace" . -}}
editable: true
access: proxy
url: {{ printf "http://%s.%s.svc:8980/opennms" $srv $namespace }}
basicAuth: true
basicAuthUser: {{ .Values.core.configuration.http.restUsername }}
secureJsonData:
  basicAuthPassword: {{ .Values.core.configuration.http.restPassword }}
{{- end }}

{{- if gt ((.Values.grafana).replicaCount|int) 0 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config
  namespace: {{ include "namespace" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
data:
  plugins.helm.yaml: |
    apiVersion: 1
    apps:
    - type: opennms-opennms-app
      disabled: false
  datasources.helm.yaml: |
    apiVersion: 1
    datasources:
    - name: OpenNMS-Performance
      type: opennms-performance-datasource
      isDefault: true
      {{- include "core.grafanaDSOptions" . | nindent 6 }}
    - name: OpenNMS-Entity
      type: opennms-entity-datasource
      {{- include "core.grafanaDSOptions" . | nindent 6 }}
    - name: OpenNMS-Flow
      type: opennms-flow-datasource
      {{- include "core.grafanaDSOptions" . | nindent 6 }}

{{- end }}
