{{- if .Values.core.inspector.enabled }}
{{- $image := printf "%s:%s" .Values.core.image.repository (.Values.core.image.tag | default .Values.opennmsVersion) -}}
---
apiVersion: v1
kind: Pod
metadata:
  name: inspector
  namespace: {{ .Release.Name }}
  labels:
    app: onms-inspector
    {{- include "core.labels" . | nindent 4 }}  
spec:
  containers:
  - name: inspector
    image: {{ $image }}
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: etc
      mountPath: /opt/opennms/etc
    {{- if (include "core.enable_tss_rrd" .) }}
    - name: rrd
      mountPath: /opennms-data/rrd
    {{- end }}      
    {{- if .Values.core.configuration.storage.mibs }}
    - name: mibs
      mountPath: /opt/opennms/share/mibs
    {{- end }}

  volumes:
  - name: etc
    persistentVolumeClaim:
      claimName: onms-etc-pvc
  {{- if (include "core.enable_tss_rrd" .) }}
  - name: rrd
    persistentVolumeClaim:
      claimName: onms-rrd-pvc
      readOnly: false
  {{- end }}
  {{- if .Values.core.configuration.storage.mibs }}
  - name: mibs
    persistentVolumeClaim:
      claimName: onms-mibs-pvc
      readOnly: false
  {{- end }}
{{- end }}