{{- if and .Values.releaseNamespace .Values.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "namespace" . }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
{{- end }}
