{{- if and .Values.createNamespace (not (eq .Release.Name "default")) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "core.labels" . | nindent 4 }}
{{- end }}
