---
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: onms-post-config
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    {{- include "core.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ (.Values.core.postConfigJob.ttlSecondsAfterFinished | default "300") }}
  template:
    spec:
      restartPolicy: Never
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $k, $r := .Values.imagePullSecrets }}
        - name: {{ $r.name }}
        {{- end }}
      {{- end }}
      containers:
      - name: init
        image: {{ printf "%s:%s" .Values.core.image.repository (.Values.core.image.tag | default .Chart.AppVersion) }}
        imagePullPolicy: IfNotPresent
        command: [ bash, /scripts/onms-post-init.sh ]
        envFrom:
        - configMapRef:
            name: app-settings
        - secretRef:
            name: app-credentials
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: app-scripts
