{{- if gt ((.Values.sentinel).replicaCount|int) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: {{ .Release.Name }}
  labels:
    app: onms-sentinel
    {{- include "core.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: karaf
    protocol: TCP
    port: 8301
    targetPort: karaf
  - name: http
    protocol: TCP
    port: 8181
    targetPort: http
  selector:
    app: onms-sentinel
{{- end}}