---
apiVersion: v1
kind: Service
metadata:
  name: onms-core
  namespace: {{ include "namespace" . }}
  labels:
    app: onms-core
    {{- include "core.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  {{- if .Values.core.configuration.ports.karaf.enabled }}
  - port: {{ .Values.core.configuration.ports.karaf.externalPort | default 8101 }}
    name: karaf
    targetPort: 8101
  {{- end }}
  {{- if .Values.core.configuration.ports.trapd.enabled }}
  - port: {{ .Values.core.configuration.ports.trapd.externalPort | default 1162 }}
    name: trapd
    protocol: UDP
    targetPort: 1162
  {{- end }}
  {{- if .Values.core.configuration.ports.syslog.enabled }}
  - port: {{ .Values.core.configuration.ports.syslog.externalPort | default 10514 }}
    name: syslog
    protocol: UDP
    targetPort: 10514
  {{- end }}
  selector:
    app: onms-core
    {{- include "core.selectorLabels" . | nindent 4 }}
