---
apiVersion: v1
kind: Service
metadata:
  name: onms-core
  namespace: {{ .Release.Name }}
  labels:
    app: onms-core
    {{- include "core.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - port: 8980
    name: http
  - port: 8101
    name: karaf
  - port: 1116
    name: trapd
    protocol: UDP
  - port: 10514
    name: syslog
    protocol: UDP
  selector:
    app: onms-core
    {{- include "core.selectorLabels" . | nindent 4 }}
