{{- if (include "core.enableTssDualWrite" .) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: onms-rrd-pvc
  namespace: {{ include "namespace" . }}
  labels:
    app: onms-core
    tier: storage
    {{- include "core.labels" . | nindent 4 }}
spec:
  accessModes: # Assumes default StorageClass
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.core.configuration.storage.rrd | default "1000Gi" }}
{{- end }}
