{{- if eq (include "onOpenShift" .) "true" }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "system:openshift:scc:%s" (.Values.dependencies.securitycontext).securitycontextconstraints.name | quote }} 
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - {{ (.Values.dependencies.securitycontext).securitycontextconstraints.name | quote }}
{{- end }}