{{- if and (eq (include "onOpenShift" .) "true") ((.Values.dependencies.securitycontext).serviceaccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sneakyminion
  namespace: {{ .Release.Name }}
{{- end }}